import Image from 'next/image'
import { useEffect } from 'react'

import { Container } from '@mui/system'
import { motion } from 'framer-motion'
import styles from '../components/Projects/projects.module.scss'

import { titleAnimate } from '../util/animation'
import { supabase } from '../util/supabaseClient'

import Hero from '../public/img/layout/projects.png'
import Title from '../public/img/layout/nahana_title.svg'
import ProjectsSide from '../public/img/layout/projects.svg'
import Featured from '../components/Projects/Featured'
import Archive from '../components/Projects/Archive'

const FADE_UP = {
	initial: {
		y: 100,
		opacity: 0,
	},
	animate: {
		y: 0,
		opacity: 1,
		transition: { ease: 'easeInOut', duration: 0.75 },
	},
}

const SLIDE_RIGHT = {
	initial: {
		x: -50,
		opacity: 0,
	},
	animate: {
		x: 0,
		opacity: 1,
		transition: { ease: 'easeInOut', duration: 0.75 },
	},
}

const SLIDE_LEFT = {
	initial: {
		x: 50,
		opacity: 0,
	},
	animate: {
		x: 0,
		opacity: 1,
		transition: { ease: 'easeInOut', duration: 0.75 },
	},
}
const Projects = ({ featured }) => {
	const json = [
		// {
		// 	id: '119',
		// 	project: 'Daily 01-10-21',
		// 	url: 'daily21-0110',
		// 	tags: '["cg","type"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'Cinema 4D, Octane, Adobe Photoshop',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2021-01-11',
		// },
		// {
		// 	id: '114',
		// 	project: 'Daily 01-05-21',
		// 	url: 'daily21-0105',
		// 	tags: '["cg","motion","gfx"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'Cinema 4D, Octane, After Effects',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: '1',
		// 	date: '2021-01-05',
		// },
		{
			id: '113',
			project: 'CYM Lighting',
			url: 'cym',
			tags: '["web"]',
			agency: 'freelance',
			role: 'Web Developer',
			tools: 'React, ES6 Javascript, HTML5, CSS3, SASS, Adobe XD',
			extra: 'CYMLighting.com</a>',
			feature: null,
			images: '1',
			video: null,
			date: '2020-09-01',
		},
		// {
		// 	id: '112',
		// 	project: 'Daily Drift Wood',
		// 	url: 'daily_drift',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane, Quixel Bridge, Quixel Mixer',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2020-06-14',
		// },
		{
			id: '120',
			project: 'Kitchen Reno',
			url: 'kitchen_reno_01',
			tags: '["previz"]',
			agency: 'freelance',
			role: '3D Rendering, Design & Finishing ',
			tools: 'CINEMA 4D, Octane, Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2020-03-12',
		},
		{
			id: '122',
			project: 'Poker Masters Wall Design',
			url: 'pokermaster',
			tags: '["gfx"]',
			agency: 'ISD',
			role: 'Creative Direction, Graphic Layout and Design',
			tools: 'Photoshop, Illustrator',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2019-10-10',
		},
		{
			id: '78',
			project: 'Riot Streaming Studio',
			url: 'riot_studio',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA 4D, Vectorworks, Octane',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2019-07-19',
		},
		{
			id: '105',
			project: 'Artisan Acres',
			url: 'artisan_acres',
			tags: '["gfx","logo","branding","web"]',
			agency: 'ISD',
			role: 'Web Development, Branding, Logo Design',
			tools: 'HTML5, CSS3, Bootstrap, Javascript, JQuery, PHP, Responsive Design, Illustrator, Photoshop',
			extra: 'ArtisanAcres.com</a>',
			feature: null,
			images: '1',
			video: null,
			date: '2019-04-01',
		},
		{
			id: '22',
			project: 'News Studio Concept',
			url: 'news_room_one',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA 4D, Octane',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2019-03-27',
		},
		{
			id: '23',
			project: 'News Studio Concept',
			url: 'news_room_two',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA 4D, Octane',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2019-03-27',
		},
		{
			id: '25',
			project: 'Studio E Concept',
			url: 'studio_e',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA 4D, Octane',
			extra: '',
			feature: '1',
			images: '1',
			video: null,
			date: '2019-03-05',
		},
		{
			id: '90',
			project: 'ISD CG Reel',
			url: 'isd_cg_reel',
			tags: '["motion"]',
			agency: 'ISD',
			role: 'Creative Direction, Rendering, Editing',
			tools: 'CINEMA 4D, After Effects',
			extra: '',
			feature: null,
			images: null,
			video: '1',
			date: '2018-10-01',
		},
		{
			id: '91',
			project: 'ISD Show Reel',
			url: 'isd_show_reel',
			tags: '["motion"]',
			agency: 'ISD',
			role: 'Creative Direction, Editing',
			tools: 'After Effects',
			extra: '',
			feature: null,
			images: null,
			video: '1',
			date: '2018-10-01',
		},
		// {
		// 	id: '5',
		// 	project: 'Daily 23',
		// 	url: 'daily_023',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane, X-Particles',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2018-08-28',
		// },
		// {
		// 	id: '4',
		// 	project: 'Daily 21',
		// 	url: 'daily_021',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane, X-Particles',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2018-08-26',
		// },
		{
			id: '121',
			project: 'Omnicron Concept',
			url: 'omnicron',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA 4D, Octane, Vectorworks, Photoshop',
			extra: '',
			feature: null,
			images: null,
			video: null,
			date: '2018-08-17',
		},
		// {
		// 	id: '3',
		// 	project: 'Daily 11',
		// 	url: 'daily_011',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2018-08-16',
		// },
		// {
		// 	id: '2',
		// 	project: 'Daily 10',
		// 	url: 'daily_010',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: '1',
		// 	images: '1',
		// 	video: null,
		// 	date: '2018-08-15',
		// },
		{
			id: '24',
			project: 'PokerGo Studio',
			url: 'pokergo_studio',
			tags: '["scenic","previz","motion"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering, Graphic Design',
			tools: 'CINEMA 4D, Octane, Illustrator, Photoshop, Vectorworks',
			extra: '',
			feature: null,
			images: '1',
			video: '1',
			date: '2018-02-18',
		},
		{
			id: '80',
			project: 'Super Bowl 52',
			url: 'super_bowl_52',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA 4D, Vectorworks, Photoshop, Illustrator',
			extra: '',
			feature: '1',
			images: '1',
			video: null,
			date: '2018-01-18',
		},
		// {
		// 	id: '76',
		// 	project: 'Daily 37',
		// 	url: 'daily_37',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-11',
		// },
		// {
		// 	id: '75',
		// 	project: 'Daily 36',
		// 	url: 'daily_36',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-10',
		// },
		// {
		// 	id: '74',
		// 	project: 'Daily 35',
		// 	url: 'daily_35',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: 'Model by c4th at https://www.myminifactory.com/object/overwatch-d-va-meka-victory-pose-43959',
		// 	feature: null,
		// 	images: null,
		// 	video: null,
		// 	date: '2017-09-09',
		// },
		// {
		// 	id: '73',
		// 	project: 'Daily 34',
		// 	url: 'daily_34',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-08',
		// },
		// {
		// 	id: '72',
		// 	project: 'Daily 33',
		// 	url: 'daily_33',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-07',
		// },
		// {
		// 	id: '71',
		// 	project: 'Daily 32',
		// 	url: 'daily_32',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-06',
		// },
		// {
		// 	id: '70',
		// 	project: 'Daily 31',
		// 	url: 'daily_31',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-05',
		// },
		// {
		// 	id: '69',
		// 	project: 'Daily 30',
		// 	url: 'daily_30',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-04',
		// },
		// {
		// 	id: '68',
		// 	project: 'Daily 29',
		// 	url: 'daily_29',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-03',
		// },
		// {
		// 	id: '67',
		// 	project: 'Daily 28',
		// 	url: 'daily_28',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-02',
		// },
		// {
		// 	id: '66',
		// 	project: 'Daily 27',
		// 	url: 'daily_27',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-09-01',
		// },
		// {
		// 	id: '65',
		// 	project: 'Daily 26',
		// 	url: 'daily_26',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane, X-Particles',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-31',
		// },
		// {
		// 	id: '64',
		// 	project: 'Daily 25',
		// 	url: 'daily_25',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane, X Particles, Photoshop',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-30',
		// },
		// {
		// 	id: '61',
		// 	project: 'Daily 24',
		// 	url: 'daily_024',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane, X-Particles',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-28',
		// },
		// {
		// 	id: '63',
		// 	project: 'Daily 22',
		// 	url: 'daily_22',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane, X Particles, Photoshop',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-27',
		// },
		// {
		// 	id: '62',
		// 	project: 'Daily 20',
		// 	url: 'daily_20',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane, X-Particles',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-25',
		// },
		// {
		// 	id: '77',
		// 	project: 'Daily 19',
		// 	url: 'daily_019',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane, X-Particles',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-24',
		// },
		// {
		// 	id: '60',
		// 	project: 'Daily 18',
		// 	url: 'daily_018',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D , Octane, X-Particles',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-23',
		// },
		// {
		// 	id: '59',
		// 	project: 'Daily 17',
		// 	url: 'daily_017',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: 'Tracer model by c4th at https://www.myminifactory.com/object/overwatch-tracer-full-figure-42704?storeview=shop',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-22',
		// },
		// {
		// 	id: '58',
		// 	project: 'Daily 16',
		// 	url: 'daily_016',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-21',
		// },
		// {
		// 	id: '57',
		// 	project: 'Daily 15',
		// 	url: 'daily_015',
		// 	tags: '["cg","motion"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: null,
		// 	video: '1',
		// 	date: '2017-08-20',
		// },
		// {
		// 	id: '56',
		// 	project: 'Daily 14',
		// 	url: 'daily_14',
		// 	tags: '["cg","motion"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: null,
		// 	video: '1',
		// 	date: '2017-08-19',
		// },
		// {
		// 	id: '55',
		// 	project: 'Daily 13',
		// 	url: 'daily_13',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-18',
		// },
		// {
		// 	id: '1',
		// 	project: 'Daily 09',
		// 	url: 'daily_009',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-17',
		// },
		// {
		// 	id: '54',
		// 	project: 'Daily 02',
		// 	url: 'daily_012',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-17',
		// },
		// {
		// 	id: '53',
		// 	project: 'Daily 08',
		// 	url: 'daily_008',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-13',
		// },
		// {
		// 	id: '51',
		// 	project: 'Daily 04',
		// 	url: 'daily_004',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-09',
		// },
		// {
		// 	id: '50',
		// 	project: 'Daily 01',
		// 	url: 'daily_001',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Cycles 4D',
		// 	extra: '',
		// 	feature: null,
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-08-06',
		// },
		{
			id: '81',
			project: 'Universal Open',
			url: 'universal_open',
			tags: '["scenic","previz","gfx"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering, Graphic Designer',
			tools: 'CINEMA 4D, Octane, Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2017-08-04',
		},
		{
			id: '82',
			project: 'Mobile Masters',
			url: 'mobile_masters',
			tags: '["scenic","previz","motion"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering, Graphic Design',
			tools: 'CINEMA 4D, Octane, After Effects, Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: '1',
			date: '2017-05-31',
		},
		{
			id: '83',
			project: 'College Football Hall of Fame Display',
			url: 'hof',
			tags: '["previz","motion","gfx"]',
			agency: 'ISD',
			role: 'Graphic Design, Previz Rendering',
			tools: 'CINEMA 4D, After Effects, Photoshop',
			extra: '',
			feature: '1',
			images: '1',
			video: '1',
			date: '2017-02-14',
		},
		// {
		// 	id: '52',
		// 	project: 'Daily 07',
		// 	url: 'daily_007',
		// 	tags: '["cg"]',
		// 	agency: 'self',
		// 	role: '',
		// 	tools: 'CINEMA 4D, Octane ',
		// 	extra: '',
		// 	feature: '1',
		// 	images: '1',
		// 	video: null,
		// 	date: '2017-02-12',
		// },
		{
			id: '93',
			project: 'Jellyfish',
			url: 'jelly_fish',
			tags: '["cg"]',
			agency: 'self',
			role: '',
			tools: 'CINEMA 4D, Photoshop ',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2016-12-09',
		},
		{
			id: '97',
			project: 'Bend and Break',
			url: 'bend_and_break',
			tags: '["gfx","type"]',
			agency: 'self',
			role: '',
			tools: 'Illustrator, Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2016-11-17',
		},
		{
			id: '102',
			project: 'To The Moon And Back',
			url: 'to_the_moon',
			tags: '["gfx","type"]',
			agency: 'self',
			role: '',
			tools: 'Photoshop, Illustrator',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2016-11-06',
		},
		{
			id: '104',
			project: 'Innovative Show Design',
			url: 'isd',
			tags: '["gfx","logo","branding","web"]',
			agency: 'ISD',
			role: 'Web Development, Branding, Logo Design',
			tools: 'HTML5, CSS3, Bootstrap, Javascript, JQuery, PHP, Responsive Design, Illustrator, Photoshop',
			extra: 'iShowDesign.com</a>',
			feature: null,
			images: '1',
			video: null,
			date: '2016-10-01',
		},
		{
			id: '115',
			project: 'College Football Awards',
			url: 'cfa',
			tags: '["gfx"]',
			agency: 'ISD',
			role: 'Creative Direction',
			tools: 'Cinema 4D, Adobe Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2016-09-01',
		},
		{
			id: '79',
			project: 'World Series of Poker',
			url: 'wsop',
			tags: '["scenic","previz","motion"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering, Graphic Designer',
			tools: 'CINEMA 4D, Octane, Illustrator, After Effects',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2016-06-04',
		},
		{
			id: '101',
			project: 'Seasons',
			url: 'seasons',
			tags: '["gfx"]',
			agency: 'self',
			role: '',
			tools: 'Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2016-05-12',
		},
		{
			id: '84',
			project: 'Kim Komando',
			url: 'kim_komando',
			tags: '["scenic","previz","motion"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering, Graphic Design',
			tools: 'CINEMA 4D, After Effects, Photoshop, Illustrator',
			extra: '',
			feature: null,
			images: '1',
			video: '1',
			date: '2015-10-09',
		},
		{
			id: '85',
			project: 'Football Night In America',
			url: 'fbna',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA 4D',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2015-09-10',
		},
		{
			id: '106',
			project: 'Snap Cutlery',
			url: 'snap',
			tags: '["gfx","logo","branding","web"]',
			agency: 'freelance',
			role: 'Web Development, Branding, Logo Design',
			tools: 'HTML5, CSS3, Bootstrap, Javascript, JQuery, PHP, Responsive Design, Illustrator, Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2015-06-11',
		},
		{
			id: '107',
			project: 'Crosscreek',
			url: 'crosscreek',
			tags: '["gfx","logo","branding","web"]',
			agency: 'freelance',
			role: 'Web Development, Logo Design',
			tools: 'HTML5, CSS3, Bootstrap, Javascript, JQuery, PHP, Responsive Design, Illustrator, Photoshop',
			extra: '',
			feature: '1',
			images: '1',
			video: null,
			date: '2014-07-24',
		},
		{
			id: '86',
			project: 'NFL Draft Desk',
			url: 'nfl_draft',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA4D',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2014-04-29',
		},
		{
			id: '87',
			project: 'Super Bowl 49',
			url: 'super_bowl_49',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering',
			tools: 'CINEMA 4D',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2014-02-01',
		},
		{
			id: '111',
			project: 'Angel Envy',
			url: 'angel_envy',
			tags: '["gfx","logo","branding"]',
			agency: 'freelance',
			role: 'Logo Design, Branding',
			tools: 'Illustrator, Photoshop, InDesign',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2013-10-01',
		},
		{
			id: '103',
			project: 'Serene',
			url: 'serene',
			tags: '["gfx","type"]',
			agency: 'self',
			role: '',
			tools: 'Photoshop, Illustrator',
			extra: '',
			feature: null,
			images: null,
			video: null,
			date: '2013-05-22',
		},
		{
			id: '110',
			project: 'Bella Vie Hair Salon',
			url: 'bella_vie',
			tags: '["gfx","logo","branding","web"]',
			agency: 'freelance',
			role: 'Web Development, Logo Design, Branding',
			tools: 'Photoshop, Illustrator, InDesign',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2013-05-01',
		},
		{
			id: '88',
			project: 'UFC Ultimate Insider',
			url: 'ufc',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction',
			tools: 'CINEMA 4D',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2013-01-07',
		},
		{
			id: '89',
			project: 'NBA TV',
			url: 'nba_tv',
			tags: '["scenic","previz"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering, Graphic Design',
			tools: 'CINEMA 4D, Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2012-10-15',
		},
		{
			id: '109',
			project: 'Hair Canvas',
			url: 'hair_canvas',
			tags: '["gfx","logo","branding"]',
			agency: 'freelance',
			role: 'Branding, Logo Design',
			tools: 'Illustrator, Photoshop, InDesign',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2012-10-01',
		},
		{
			id: '95',
			project: 'Art Is Long',
			url: 'art_is_long',
			tags: '["gfx","type"]',
			agency: 'self',
			role: '',
			tools: 'Illustrator, Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2012-06-02',
		},
		{
			id: '116',
			project: 'Hockey Central',
			url: 'hockey_central',
			tags: '["scenic","previz","gfx"]',
			agency: 'ISD',
			role: 'Creative Direction, Previz Rendering, Graphic Design',
			tools: 'Cinema 4D, Adobe Photoshop',
			extra: '',
			feature: null,
			images: '1',
			video: null,
			date: '2011-11-01',
		},
	]

	// useEffect(() => {
	// 	const db = async () => {
	// 		// let role_array = []
	// 		// data returns the insert info with ID

	// 		const TOOLS = await SUPABASE.from('Tools').select()
	// 		const ROLES = await SUPABASE.from('Roles').select()
	// 		console.log(TOOLS)

	// 		json.map(async ele => {
	// 			let insert = {
	// 				ProjectName: ele.project,
	// 				Date: ele.date,
	// 			}
	// 			const { data, error } = await SUPABASE.from('Projects').insert(
	// 				insert
	// 			)
	// 			let roles = ele.role.split(', ')

	// 			let roleInsert = roles.map(ele => {
	// 				let role = ROLES.data.find(r => r.Role === ele)
	// 				return {
	// 					ProjectId: data[0].ProjectId,
	// 					RoleId: role.RoleId,
	// 				}
	// 			})
	// 			const ROLE_INSERT = await SUPABASE.from('ProjectRoles').insert(
	// 				roleInsert
	// 			)
	// 			// console.log(ROLE_INSERT)

	// 			let tools = ele.tools.split(', ')
	// 			let toolInsert = tools.map(ele => {
	// 				// console.log('---', ele)
	// 				let tool = TOOLS.data.find(t => t.Tool === ele)
	// 				return {
	// 					ProjectId: data[0].ProjectId,
	// 					ToolId: tool.ToolId,
	// 				}
	// 			})
	// 			const TOOL_INSERT = await SUPABASE.from('ProjectTools').insert(
	// 				toolInsert
	// 			)
	// 		})

	// 		// let unique = [...new Set(role_array)]
	// 		// let roleInsert = unique.map(e => {
	// 		// 	return {
	// 		// 		Role: e,
	// 		// 	}
	// 		// })
	// 		// console.log(roleInsert)

	// 		// const { data, error } = await SUPABASE.from('Projects').insert([
	// 		// 	{ ProjectName: 'CYM Lighting' },
	// 		// ])
	// 		// console.log(data, error)
	// 	}
	// 	db()
	// }, [])

	useEffect(() => {
		titleAnimate()
	}, [])

	return (
		<>
			<motion.section
				className={styles.projects}
				initial="initial"
				animate="animate"
			>
				<motion.div variants={SLIDE_RIGHT}>
					<Title className={styles.title} />
				</motion.div>
				<motion.div variants={SLIDE_LEFT}>
					<ProjectsSide className={styles.sideTitle} />
				</motion.div>

				<Container
					maxWidth="xl"
					fixed
					className={styles.container}
					disableGutters={true}
				>
					<div className={styles.heroContainer}>
						<div className={styles.imageContainer}>
							<Image
								className={styles.hero}
								src={Hero}
								width={1372}
								height={836}
								layout="responsive"
								alt="Projects"
								placeholder="blur"
							/>
						</div>
					</div>

					<div className={styles.featured}>
						{featured.map((ele, i) => {
							let alt = i % 2 === 0 ? false : true

							return (
								<Featured
									key={ele.ProjectId}
									title={ele.ProjectName}
									alt={alt}
									url={ele.URL}
								/>
							)
						})}
					</div>
					<Archive />
				</Container>
			</motion.section>
		</>
	)
}

export default Projects

export const getServerSideProps = async () => {
	const { data } = await supabase
		.from('Projects')
		.select()
		.order('ProjectId')
		.eq('Featured', true)

	return {
		props: {
			featured: data,
		},
	}
}
